/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames.internal;

import dbaccess.DBGetter;
import dbaccess.DBInserter;
import dbaccess.DBUpdater;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import models.EmployeeDetails;
import utilities.OtherUtilities;

/**
 *
 * @author hrox
 */
public class EmployeeMaster extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmployeeMaster
     */
    boolean epfCheck = true;
    boolean etfCheck = true;

    int permanentState = 0;
    int monthlyState = 0;
    int paybleState = 0;
    int marriedState = 0;

    boolean updated = false;

    JDesktopPane jdp = new JDesktopPane();

    public EmployeeMaster(JDesktopPane jdp) {
        initComponents();

        this.jdp = jdp;

        //hide controls
        btnDelete.setVisible(false);
        jtfAppDate.setVisible(false);
        jtfDOB.setVisible(false);
        jtfExpDate.setVisible(false);

        //get next employee no
        jtfEmpId.setText("" + DBGetter.getNextEmployeeId());

    }

    public EmployeeMaster(JDesktopPane jdp, EmployeeDetails emp, boolean updated) {
        initComponents();

        this.jdp = jdp;
        this.updated = updated;

        //set values to controls
        jtfAddr1.setText(emp.getAddress1());
        jtfAddr2.setText(emp.getAddress2());
        jtfAddr3.setText(emp.getAddress3());
        jtfAppDate.setText(emp.getFirstAppointmentDate());
        jtfCitizenship.setText(emp.getCitizenship());
        jtfContact1.setText(emp.getContact1());
        jtfContact2.setText(emp.getContact2());
        jtfContact3.setText(emp.getContact3());
        jtfDOB.setText(emp.getDob());
        jtfEmpId.setText(emp.getEmpId() + "");
        jtfEmpName.setText(emp.getEmpName());
        jtfEpf.setText(emp.getEpfNo());
        jtfEtf.setText(emp.getEtfNo());
        jtfExpDate.setText(emp.getPassportExpiratonDate());
        jtfGuardian.setText(emp.getGuardianName());
        jtfGuardianContact.setText(emp.getGuardianContact());
        jtfGuardianRelationship.setText(emp.getGuardianRelation());
        jtfNic.setText(emp.getNic());
        jtfPassportNo.setText(emp.getPassportNo());
        jcbGender.setSelectedItem(emp.getGender());

        this.permanentState = emp.getIsPermanent();
        this.paybleState = emp.getIsPaid();
        this.marriedState = emp.getIsMarried();
        this.monthlyState = emp.getIsMonthly();

        if (this.permanentState == 1) {
            chkPermanent.setSelected(true);
        } else {
            chkPermanent.setSelected(false);
        }

        if (this.paybleState == 1) {
            chkPayble.setSelected(true);
        } else {
            chkPayble.setSelected(false);
        }

        if (this.marriedState == 1) {
            chkMarried.setSelected(true);
        } else {
            chkMarried.setSelected(false);
        }

        if (this.monthlyState == 1) {
            chkMonthly.setSelected(true);
        } else {
            chkMonthly.setSelected(false);
        }

        //show controls
        btnDelete.setVisible(true);
        btnSave.setText("Update");

        //hide controls
        jdcAppDate.setVisible(false);
        jdcDob.setVisible(false);
        jdcPExpDate.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfEmpId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfEpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfEtf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        chkPermanent = new javax.swing.JCheckBox();
        chkPayble = new javax.swing.JCheckBox();
        chkMonthly = new javax.swing.JCheckBox();
        jdcAppDate = new com.toedter.calendar.JDateChooser();
        jtfAppDate = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfEmpName = new javax.swing.JTextField();
        jtfNic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbGender = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jdcDob = new com.toedter.calendar.JDateChooser();
        chkMarried = new javax.swing.JCheckBox();
        jtfDOB = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jtfAddr1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfAddr2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfAddr3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfContact1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfContact2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfContact3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtfGuardian = new javax.swing.JTextField();
        jtfGuardianContact = new javax.swing.JTextField();
        jtfGuardianRelationship = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jtfCitizenship = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtfPassportNo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jdcPExpDate = new com.toedter.calendar.JDateChooser();
        jtfExpDate = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Employee Details");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Company Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Employee ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 33, -1, -1));

        jtfEmpId.setEditable(false);
        jPanel1.add(jtfEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 31, 100, -1));

        jLabel3.setText("EPF No");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 33, -1, -1));

        jtfEpf.setText("N/A");
        jtfEpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfEpfFocusGained(evt);
            }
        });
        jPanel1.add(jtfEpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 31, 100, -1));

        jLabel4.setText("ETF No");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 33, -1, -1));

        jtfEtf.setText("N/A");
        jtfEtf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfEtfFocusGained(evt);
            }
        });
        jPanel1.add(jtfEtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 31, 100, -1));

        jLabel5.setText("Appointment Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 33, -1, -1));

        chkPermanent.setText("Permanent");
        chkPermanent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPermanentActionPerformed(evt);
            }
        });
        jPanel1.add(chkPermanent, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 59, -1, -1));

        chkPayble.setText("Payable");
        jPanel1.add(chkPayble, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 59, -1, -1));

        chkMonthly.setText("Monthly");
        jPanel1.add(chkMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 59, -1, -1));
        jPanel1.add(jdcAppDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 140, -1));

        jtfAppDate.setText("jTextField1");
        jPanel1.add(jtfAppDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 140, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "General Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Employee Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 35, -1, -1));

        jLabel6.setText("NIC");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 35, -1, -1));

        jtfEmpName.setToolTipText("");
        jPanel2.add(jtfEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 33, 200, -1));

        jtfNic.setToolTipText("");
        jPanel2.add(jtfNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 33, 200, -1));

        jLabel7.setText("Gender");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 35, -1, -1));

        jcbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel2.add(jcbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 31, 153, -1));

        jLabel8.setText("DOB");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 72, -1, -1));
        jPanel2.add(jdcDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 68, 200, -1));

        chkMarried.setText("Married");
        jPanel2.add(chkMarried, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 64, -1, -1));

        jtfDOB.setText("jTextField1");
        jPanel2.add(jtfDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Contact Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel9.setText("Address 1");

        jLabel10.setText("Address 2");

        jLabel11.setText("Address 3");

        jLabel12.setText("Contact 1");

        jLabel13.setText("Contact 2");

        jLabel14.setText("Contact 3");

        jLabel15.setText("Guardian");

        jLabel16.setText("G.Contact");

        jLabel17.setText("G.Relationship");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(15, 15, 15)
                        .addComponent(jtfAddr1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfContact1)
                            .addComponent(jtfGuardian))))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(15, 15, 15)
                            .addComponent(jtfAddr2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtfContact2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfGuardianContact)))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfGuardianRelationship))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(15, 15, 15)
                        .addComponent(jtfAddr3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfContact3)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfAddr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jtfAddr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jtfAddr3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtfContact1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jtfContact2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jtfContact3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jtfGuardian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfGuardianContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfGuardianRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Other Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("Citizenship");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 33, -1, -1));
        jPanel4.add(jtfCitizenship, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 31, 160, -1));

        jLabel19.setText("Passport No");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 33, -1, -1));
        jPanel4.add(jtfPassportNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 31, 160, -1));

        jLabel20.setText("Expiration Date");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 33, -1, -1));
        jPanel4.add(jdcPExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 31, 140, -1));

        jtfExpDate.setText("jTextField1");
        jtfExpDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfExpDateFocusGained(evt);
            }
        });
        jPanel4.add(jtfExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 140, -1));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnSave.setText("Insert");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch)
                    .addComponent(btnDelete)
                    .addComponent(btnSave)
                    .addComponent(btnRefresh))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfEpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEpfFocusGained
        if (epfCheck) {
            int c = JOptionPane.showConfirmDialog(this, "Do you want to take the same Employee Id to EPF No ?", "EPF No Confirmation", JOptionPane.YES_NO_OPTION);

            if (c == 0) {
                jtfEpf.setText(jtfEmpId.getText());
                epfCheck = false;
            } else {
                epfCheck = false;
                jtfEpf.setText("");
            }
        }
    }//GEN-LAST:event_jtfEpfFocusGained

    private void jtfEtfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEtfFocusGained
        if (etfCheck) {
            int c = JOptionPane.showConfirmDialog(this, "Do you want to take the same Employee Id to ETF No ?", "ETF No Confirmation", JOptionPane.YES_NO_OPTION);

            if (c == 0) {
                jtfEtf.setText(jtfEmpId.getText());
                etfCheck = false;
            } else {
                etfCheck = false;
                jtfEtf.setText("");
            }
        }
    }//GEN-LAST:event_jtfEtfFocusGained

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (chkPermanent.isSelected()) {
            permanentState = 1;
        } else {
            permanentState = 0;
        }
        if (chkMonthly.isSelected()) {
            monthlyState = 1;
        } else {
            monthlyState = 0;
        }
        if (chkPayble.isSelected()) {
            paybleState = 1;
        } else {
            paybleState = 0;
        }
        if (chkMarried.isSelected()) {
            marriedState = 1;
        } else {
            marriedState = 0;
        }

        if (updated) {
            //update code       
            EmployeeDetails emp = new EmployeeDetails();
            emp.setEmpId(Integer.parseInt(jtfEmpId.getText()));
            emp.setEpfNo(jtfEpf.getText().trim());
            emp.setEtfNo(jtfEtf.getText().trim());
            emp.setIsPermanent(permanentState);
            emp.setIsPaid(paybleState);
            emp.setIsMonthly(monthlyState);
            emp.setIsMarried(marriedState);
            emp.setAddress1(jtfAddr1.getText().trim());
            emp.setAddress2(jtfAddr2.getText().trim());
            emp.setAddress3(jtfAddr3.getText().trim());
            emp.setContact1(jtfContact1.getText().trim());
            emp.setContact2(jtfContact2.getText().trim());
            emp.setContact3(jtfContact3.getText().trim());
            emp.setGuardianName(jtfGuardian.getText().trim());
            emp.setGuardianContact(jtfGuardianContact.getText().trim());
            emp.setGuardianRelation(jtfGuardianRelationship.getText().trim());
            emp.setCitizenship(jtfCitizenship.getText().trim());
            emp.setPassportNo(jtfPassportNo.getText().trim());
            if (!emp.getPassportNo().equals("")) {
                emp.setPassportExpiratonDate(OtherUtilities.getDateFromDateChooser(jdcPExpDate));
            } else {
                emp.setPassportExpiratonDate("");
            }

            boolean employeeUpdated = DBUpdater.updateEmployeeDetails(emp);

            if (employeeUpdated) {
                JOptionPane.showMessageDialog(this, "Employee Updated Successfully !!!");
                refresh();
            }

        } else {
            //insert code
            EmployeeDetails emp = new EmployeeDetails();
            emp.setEmpId(Integer.parseInt(jtfEmpId.getText()));
            emp.setEpfNo(jtfEpf.getText().trim());
            emp.setEtfNo(jtfEtf.getText().trim());
            emp.setFirstAppointmentDate(OtherUtilities.getDateFromDateChooser(jdcAppDate));
            emp.setIsPermanent(permanentState);
            emp.setIsPaid(paybleState);
            emp.setIsMonthly(monthlyState);
            emp.setIsMarried(marriedState);
            emp.setEmpName(jtfEmpName.getText().trim());
            emp.setNic(jtfNic.getText().trim());
            emp.setGender(jcbGender.getSelectedItem().toString());
            emp.setDob(OtherUtilities.getDateFromDateChooser(jdcDob));
            emp.setAddress1(jtfAddr1.getText().trim());
            emp.setAddress2(jtfAddr2.getText().trim());
            emp.setAddress3(jtfAddr3.getText().trim());
            emp.setContact1(jtfContact1.getText().trim());
            emp.setContact2(jtfContact2.getText().trim());
            emp.setContact3(jtfContact3.getText().trim());
            emp.setGuardianName(jtfGuardian.getText().trim());
            emp.setGuardianContact(jtfGuardianContact.getText().trim());
            emp.setGuardianRelation(jtfGuardianRelationship.getText().trim());
            emp.setCitizenship(jtfCitizenship.getText().trim());
            emp.setPassportNo(jtfPassportNo.getText().trim());
            if (!emp.getPassportNo().equals("")) {
                emp.setPassportExpiratonDate(OtherUtilities.getDateFromDateChooser(jdcPExpDate));
            } else {
                emp.setPassportExpiratonDate("");
            }

            emp.setIsActive(1);

            boolean employeeInserted = DBInserter.insertEmployeeMaster(emp);

            if (employeeInserted) {
                JOptionPane.showMessageDialog(this, "Employee Inserted Successfully !!!");
                refresh();
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void chkPermanentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPermanentActionPerformed
        if (!chkPermanent.isSelected()) {
            jtfEpf.setText("N/A");
            jtfEtf.setText("N/A");
        } else {
            jtfEpf.setText(jtfEmpId.getText());
            jtfEtf.setText(jtfEmpId.getText());
        }
    }//GEN-LAST:event_chkPermanentActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        Search f = new Search(1, this, jdp);
        OtherUtilities.displayInternalFrame(f, jdp);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refresh();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jtfExpDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfExpDateFocusGained
        //enable date chooser for passport expiration date
        jtfExpDate.setVisible(false);
        jdcPExpDate.setVisible(true);
    }//GEN-LAST:event_jtfExpDateFocusGained

    void refresh() {

        jtfEmpId.setText("" + DBGetter.getNextEmployeeId());
        jtfEpf.setText("N/A");
        jtfEtf.setText("N/A");
        chkPermanent.setSelected(false);
        chkMonthly.setSelected(false);
        chkPayble.setSelected(false);
        chkMarried.setSelected(false);
        jtfEmpName.setText("");
        jtfNic.setText("");
        jtfAddr1.setText("");
        jtfAddr2.setText("");
        jtfAddr3.setText("");
        jtfContact1.setText("");
        jtfContact2.setText("");
        jtfContact3.setText("");
        jtfGuardian.setText("");
        jtfGuardianContact.setText("");
        jtfGuardianRelationship.setText("");
        jtfCitizenship.setText("");
        jtfPassportNo.setText("");
        btnDelete.setVisible(false);
        btnSave.setText("Save");

        jtfAppDate.setVisible(false);
        jtfDOB.setVisible(false);
        jtfExpDate.setVisible(false);

        jdcAppDate.setVisible(true);
        jdcDob.setVisible(true);
        jdcPExpDate.setVisible(true);

        permanentState = 0;
        monthlyState = 0;
        paybleState = 0;
        marriedState = 0;

        updated = false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox chkMarried;
    private javax.swing.JCheckBox chkMonthly;
    private javax.swing.JCheckBox chkPayble;
    private javax.swing.JCheckBox chkPermanent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> jcbGender;
    private com.toedter.calendar.JDateChooser jdcAppDate;
    private com.toedter.calendar.JDateChooser jdcDob;
    private com.toedter.calendar.JDateChooser jdcPExpDate;
    private javax.swing.JTextField jtfAddr1;
    private javax.swing.JTextField jtfAddr2;
    private javax.swing.JTextField jtfAddr3;
    private javax.swing.JTextField jtfAppDate;
    private javax.swing.JTextField jtfCitizenship;
    private javax.swing.JTextField jtfContact1;
    private javax.swing.JTextField jtfContact2;
    private javax.swing.JTextField jtfContact3;
    private javax.swing.JTextField jtfDOB;
    private javax.swing.JTextField jtfEmpId;
    private javax.swing.JTextField jtfEmpName;
    private javax.swing.JTextField jtfEpf;
    private javax.swing.JTextField jtfEtf;
    private javax.swing.JTextField jtfExpDate;
    private javax.swing.JTextField jtfGuardian;
    private javax.swing.JTextField jtfGuardianContact;
    private javax.swing.JTextField jtfGuardianRelationship;
    private javax.swing.JTextField jtfNic;
    private javax.swing.JTextField jtfPassportNo;
    // End of variables declaration//GEN-END:variables
}
