/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames.internal;

import dbaccess.DBGetter;
import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import models.EmployeeDetails;
import othermethods.StringManipulator;
import utilities.OtherUtilities;

/**
 *
 * @author hrox
 */
public class Search extends javax.swing.JInternalFrame {

    /**
     * Creates new form Search
     */
    int type = 0;

    JInternalFrame jif = new JInternalFrame();
    JDesktopPane jdp = new JDesktopPane();

    public Search() {
        initComponents();
    }

    public Search(int type, JInternalFrame jif, JDesktopPane jdp) {
        initComponents();

        this.type = type;
        this.jif = jif;
        this.jdp = jdp;

        //get all names to search box
        jList1.removeAll();
        DBGetter.getIdNamesToList(jList1, type, txbSearch.getText().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txbSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setClosable(true);
        setTitle("Search");

        jLabel1.setText("Name");

        txbSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txbSearchKeyReleased(evt);
            }
        });

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txbSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbSearchKeyReleased
        jList1.removeAll();
        DBGetter.getIdNamesToList(jList1, type, txbSearch.getText().trim());
    }//GEN-LAST:event_txbSearchKeyReleased

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if (evt.getClickCount() == 2) {
            //call the master frame
            if (type == 1) {
                if (jList1.getSelectedIndex() > -1) {
                    String[] data = StringManipulator.getIdNameSeperatelyFromItem(jList1.getSelectedValue());
                    EmployeeDetails emp = DBGetter.getEmployeeDetailsFromId(Integer.parseInt(data[0]));

                    this.jif.hide();
                    EmployeeMaster iag = new EmployeeMaster(jdp, emp, true);
                    this.hide();
                    Dimension desktopSize = this.jdp.getSize();
                    Dimension jInternalFrameSize = iag.getSize();
                    iag.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                            (desktopSize.height - jInternalFrameSize.height) / 2);
                    this.jdp.add(iag);
                    iag.show();
                }
            }
        }
    }//GEN-LAST:event_jList1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txbSearch;
    // End of variables declaration//GEN-END:variables
}
